//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationRequestOrganizationItem
    {
        public int Id { get; set; }
        public int RequestOrganizationId { get; set; }
        public int RequestItemId { get; set; }
        public double Quantity { get; set; }
        public int QuantityUOM { get; set; }
        public Nullable<double> CollectedQuantity { get; set; }
        public Nullable<int> CollectedQuantityUOM { get; set; }
        public Nullable<double> DeliveredQuantity { get; set; }
        public Nullable<int> DeliveredQuantityUOM { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
